### ISSUE TITLE
How to create the example images?

### ISSUE THREAD

**Issue by thatsIch** [thatsIch/sublime-rainmeter#11]
@merlinthered

How did you create the images? I want to keep the style, but I have to replace some of them with newer content like

![image](https://cloud.githubusercontent.com/assets/2210496/20462037/9fc38f42-af10-11e6-9fec-cda2c2e62b12.png)

any special tool/filter used?

**Comment by merlinthered** [comment]
They're just screenshots with the Monokai color scheme. I cropped them and added the shadow in Inkscape. If you want to recreate that, import the image in Inkscape, create a black rectangle of the same size in the background, blur it and move it to the right and down a little. Then export the image as a PNG.

**Comment by thatsIch** [comment]
Thank you, I made https://github.com/thatsIch/sublime-rainmeter-image-smoother in response. Though I couldnt figure the exact values out sadly, but I guess people will not notice anyways.
