### ISSUE TITLE
There is no package of rainmeter for sublime 3 in package control 

### ISSUE THREAD

**Issue by Droyk** [thatsIch/sublime-rainmeter#12]
Hey @thatsIch thanx for updating this theme to sublime 3 but why don't you add this rainmeter syntax highlighter in package control plz tell me it will easier that way to install on the machine and many user will love this way of installation.

Hope you add it & thanx again @thatsIch for updating this theme and thanx @merlinthered for creating it.

**Comment by thatsIch** [comment]
It is still getting reviewed, it takes a long time, because the maintainer want to keep the quality of packages high.

https://github.com/wbond/package_control_channel/pull/5941#issuecomment-258705358

**Comment by Droyk** [comment]
How much time approximately do you think we have to wait?

**Comment by thatsIch** [comment]
soon I guess, since it is reviewed but there are some minor issues. I already waited almost one month for that PR ^^

**Comment by Droyk** [comment]
Really glad to hear that!
