### ISSUE TITLE
Show quick outline for navigation

### ISSUE THREAD

**Issue by thatsIch** [thatsIch/sublime-rainmeter#18]
Sometimes a single `.ini` can get very big, but you know what you are searching for, but you have no clue how it is written or named. Showing a quick outline can help navigate by showing their section names and their type.

This sounds somewhat useful, but personally I have never ever used such a feature in an IDE. Open for discussion.

**Comment by eclectic-tech** [comment]
There are already 'Minimap' and the 'Find' menu to help locate items... not sure if anything more is needed?
I seldom use the 'Minimap' other than to navigate quickly to another section.

**Comment by thatsIch** [comment]
It is more like a "Jump to..." command, which will pop-up a list of all named sections (maybe even from the includes?) basically a simple filter like

* `[Rainmeter]`
* `[MyMeter]` Meter Image
* `[MyMeasure]` Measure CPU

or something along the line.

I think the Minimap is only useful if you know where the thing you search for is,
and the find. I guess this could simulate it if you are decent with regex?

**Comment by thatsIch** [comment]
It seems the `Goto` menu is intended for that. I think I will implement using that. It is not that sophisticated as I intended to be, but it should work as expected if you use `Goto -> Symbol`
