### ISSUE TITLE
Fix installation via PackageControl

### ISSUE THREAD

**Issue by thatsIch** [thatsIch/sublime-rainmeter#2]
The PackageControl PR https://github.com/wbond/package_control_channel/pull/5941 is up and functioning and just waiting to be PRed. Seems the contributers are quite busy. Over 80 PRs in queue. Let's all hope to get pulled quickly.

**Comment by thatsIch** [comment]
vor the time being you can install it via Package Control and Added Repository. Look into the release notes to read more about that matter and the readme for instructions.

**Comment by Droyk** [comment]
Atlast thanx thatslch for your hardowork now we can install it via package control.

**Comment by thatsIch** [comment]
🎉

**Comment by Droyk** [comment]
well I want to ask you something @thatsIch why do we have to install repository too?
when we just can install rainmeter package from package control and it will obviously automatically updated

did you add the repository function because package control doesn't update your rainmeter package slowly.

**Comment by thatsIch** [comment]
huh did I not close this issue already? oO

@Droyk I added the repository option to let people update it via package control without the pull request. Since it is pulled, this option is obsolete though can be used in the future if I need to introduce breaking changes.

**Comment by Droyk** [comment]
okay but what do you mean it is pulled?
I have already installed both the repository and the package should I remove the repository then.

**Comment by thatsIch** [comment]
yes, you can remove the repository, but since both are the same at the current time, it does not matter what you do.

**Comment by thatsIch** [comment]
also check the link in the first note from me,
that is the pull request. If a PR is accepted you can call it "pulled"
