### ISSUE TITLE
Update snippets to meet the latest doc

### ISSUE THREAD

**Issue by hyrious** [thatsIch/sublime-rainmeter#41]
The [snippets](https://github.com/thatsIch/sublime-rainmeter/tree/master/Snippets) were commited **5 years ago** and skin options have changed these years.
I would like to see an update according to the [latest doc](https://docs.rainmeter.net/manual/).
In fact, I've collected a list of it at [here](https://github.com/hyrious/easy-rainmeter-skin/blob/master/process_docs.rb).
If you decide to use it, make sure to run the process_docs.rb again.

Thanks.

**Comment by thatsIch** [comment]
Hey,

thats a nifty tool you created there :-) 
I am currently a bit busy, if you want to PR the current state, I can review it quicker
or you have to wait at least a week until I have some free time.

Cheers
   Ich

**Comment by thatsIch** [comment]
@hyrious 

What do you expect from the snippets? They were always meant to prime your measures and meters and not to opt out every potential option. 

Maybe only including required or non-optional options is better?

**Comment by hyrious** [comment]
@thatsIch

I was also thinking about what snippets may be more convenient, and also had some try personally (yet not put it on gh).

If only including required options, it will be necessary to write another snippets like "tpos (x/y/w/h)". Yet putting these general options in a [StyleGroup] section may be better.

**Comment by thatsIch** [comment]
I do not use any snippets, so.. I am a bit bummed. Snippets by definition require to be reusable. So they can not be totally generic (so probably only required is no-go). Maybe going by every possible meter out there is the wrong way? 

Maybe more useful snippets are the ones like the [color snippet](https://github.com/thatsIch/sublime-rainmeter/blob/master/Snippets/color.sublime-snippet).

Or maybe we just need to discuss, what is update-worthy?

**Comment by hyrious** [comment]
Maybe it's unnecessary.
