### ISSUE TITLE
WebParser classification change (cosmetic)

### ISSUE THREAD

**Issue by Aethrios** [thatsIch/sublime-rainmeter#56]
Just a heads up, 4.1 pushed WebParser to be considered both a plugin (this will be supported forever, evidently) and a measure. As I'm trying to roll my skins over to follow the new classification, I'd love to not have to see all my instances of WebParser highlighted in red like they're wrong. 

This is entirely a cosmetic change I'm looking for here. Hope this helps you stay in the loop!

Sauce: https://docs.rainmeter.net/manual/measures/webparser/#ParentChild
https://forum.rainmeter.net/viewtopic.php?f=13&t=27744

**Comment by thatsIch** [comment]
Thanks for the heads-up. I am not sure how I missed that oO

**Comment by thatsIch** [comment]
![syntax-highlighting-shaded-or8](https://user-images.githubusercontent.com/2210496/36248127-ae6b3466-1236-11e8-9030-fb91307dfd34.png)

**Comment by thatsIch** [comment]
![auto-completion-shaded-or8](https://user-images.githubusercontent.com/2210496/36248192-e6004a60-1236-11e8-9f54-780262db6dd5.png)

**Comment by thatsIch** [comment]
![removed-from-smart-completion-shaded-or8](https://user-images.githubusercontent.com/2210496/36248279-33485f7e-1237-11e8-8389-e9c978a1813a.png)

Removed the plugins from smart completion but since it still is supported we require backward compatibility.

**Comment by thatsIch** [comment]
![deprecated-shaded-or8](https://user-images.githubusercontent.com/2210496/36248597-5abea1d4-1238-11e8-8375-a0aaa0c07aee.png)

Deprecated the old plugin statements
