### ISSUE TITLE
Error Loading colour Scheme

### ISSUE THREAD

**Issue by arizq** [thatsIch/sublime-rainmeter#58]
Unablee to open package/...../tmTheme file

![screenshot 2018-05-16 22 08 30](https://user-images.githubusercontent.com/31257929/40130845-d6cd8f42-5955-11e8-9990-d1bb6caeaa9c.png)

**Comment by thatsIch** [comment]
Could you post some data to reproduce the issue?

**Comment by arizq** [comment]
I was installing from file that didnt went well but after
it got resolved when I installed from sublime package manager...
thankyou for replying

**Comment by thatsIch** [comment]
Installing from file? This sounds still like some issue, It should work though..
