### ISSUE TITLE
'SysInfo'  is now a measure

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [thatsIch/sublime-rainmeter#78]
Thank you for your work.

Your package (version 2.22.0) flags this error:

![image](https://user-images.githubusercontent.com/47056543/134831300-8620b61e-8b97-4b7c-844c-f879a1a8c134.png)

However, as of 4.5.1 - Revision 3540, [it is not an error](https://www.rainmeter.net/changes-4.5/):

![image](https://user-images.githubusercontent.com/47056543/134831248-75001a3b-c57a-4126-bf5f-80fdd171923b.png)

**Comment by thatsIch** [comment]
Thanks for reporting the news!
